version: '3.3'
services:
    web:
        image: php:7.3-apache
        build:
            context: ./phpdata
            dockerfile: Dockerfile
        container_name: web_container
        restart: always
        depends_on:
            - db
        volumes:
             - ./phpdata:/var/www/html/
        ports:
             - 8080:80
    db:
        container_name: mysql_compose
        image: mysql:latest
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: viper63
            MYSQL_DATABASE: distributed_system
            MYSQL_USER: viper63
            MYSQL_PASSWORD: viper63
        ports:
            - 3306:3306